name: Deploy Backend Batch
run-name: "🚛 CD: Deploy a batch of backend instances (Batch: ${{input.batch_id}}, Ref: ${{ inputs.ref }})"
on:
  workflow_call:
    inputs:
      ref:
        description: "Commit ref that triggered this deployment"
        required: true
        type: string
      batch_id:
        description: "Current batch number (0-9)"
        type: number
        required: true
        default: 0
      batch_size:
        description: "Quantity of instances that should be deployed in this batch"
        type: number
        required: true
        default: 1
      max_batch_id: # need a better name
        description: "The maximum batch id"
        type: number
        required: true
        default: 0
      target_loadbalancer:
        description: "The load balancer id for the newly provisioned instances"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_PRIVATE_KEY:
        required: true
    outputs:
      backend_url:
        value: ${{ jobs.provision.outputs.backend_url }}

jobs:
  deploy:
    uses: ./.github/workflows/cd-deploy-single-backend-batch.yml
    with: 
      ref: ${{ github.sha }}  
      batch_id: 0
      batch_size: 1
      target_loadbalancer: some_elb  #get this from where?
    secrets: inherit
    
  cleanup-old:
    needs: [deploy]
    uses: ./.github/workflows/cd-cleanup-backend.yml
    with: 
      # ref: ${{ needs.promote.outputs.previous_ref }}
      #env_name: Previous Blue
      reason: decommissioning
      batch_id: 0
      batch_size: 1
      target_loadbalancer: some_elb  
    secrets: inherit

  calculate_next_batch_id:    
    runs-on: ubuntu-latest
    steps:
      - name: Store next batch id
        env:
          current_batch_id: ${{ inputs.batch_id }}
        run: |
          echo "next_batch_id=$(($current_batch_id + 1))" >> $GITHUB_ENV
        
  dispatch_next_batch:
    needs: [calculate_next_batch_id]
    uses: ./.github/workflows/deploy-backend-batch.yml
    with: 
      ref: ${{ github.sha }}  
      batch_id: ${{ github.env.next_batch_id }}
      batch_size: ${{ inputs.batch_size }}
      max_batch_id: ${{ inputs.max_batch_id }}
      target_loadbalancer: some_elb  
    secrets: inherit
    