---
- name: Install Node.js via snap (faster)
  become: true
  community.general.snap:
    name: node
    classic: true
    channel: "18/stable"

- name: Install pm2
  become: true
  community.general.npm:
    name: pm2
    global: true
    production: true
    state: present