---
- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: "yes"

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: true
  ansible.builtin.npm:
    name: pm2
    global: yes
    production: yes
    state: present