---
- name: Install Node.js and npm
  become: true
  ansible.builtin.apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: false

- name: Install pm2
  become: true
  community.general.npm:
    name: pm2
    global: true
    production: true
    state: present