---
- name: Deploy Backend Artifact
  ansible.builtin.synchronize: # "copy" takes too long!
    src: "../../backend/build"
    dest: ~/anyhasher

- name: Start Server
  ansible.builtin.shell: "cd ~/anyhasher/build && pm2 start server.js --node-args='-r dotenv/config'"
