name: Deploy new version of backend
run-name: "🚛 CD: Rolling Out New Backend Version (${{ inputs.version }})"

on:
  workflow_call:
    inputs:
      version:
        description: "The version of this deployment (ex: git commit sha)"
        required: true
        type: string

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Use commit workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: util/terraform
          workspace: anyhasher-backend-${{ inputs.version }}

      - name: Set version in tfvars
        run: |
          echo -e 'ver="${{ inputs.version }}"\n' >> util/terraform/environments/prod/main.tfvars
          cat util/terraform/environments/prod/main.tfvars

      - name: Apply Infra Code
        id: apply_changes
        uses: dflook/terraform-apply@v2
        with:
          workspace: anyhasher-backend-${{ inputs.version }}
          auto_approve: true
          var_file: |
            util/terraform/environments/prod/main.tfvars
          path: util/terraform/

  configure:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact-${{ inputs.ref }}
          path: backend/build/
          
      - name: Fetch EC2 Hosts
        run: ../util/scripts/fetch-ec2-by-tag.sh $VERSION

      - name: Configure Backends
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./util/ansible
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          options: |
            --verbose
            --inventory ./inventory/hosts
                  
  wait_for_health:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Wait for ALB Health Checks
        run: ../util/scripts/wait-for-alb.sh ${{ secrets.ALB_TARGET_GROUP_ARN }}

  smoke_test:
    needs: wait_for_health
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
    steps:
      - name: Run Smoke Tests
        run: ../util/scripts/smoke-test.sh https://api.anyhasher.com $VERSION

  cleanup:
    needs: smoke_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Previous ASG
        run: ../util/scripts/get-previous-asg.sh prod $VERSION
      
      - name: Destroy Old ASG
        run: ../util/scripts/destroy-old-asg.sh prod $PREVIOUS_ASG_NAME
  
  # rollback: 
