name: Deploy new version of backend
run-name: "🚛 CD: Rolling Out New Backend Version (${{ inputs.version }})"

on:
  workflow_call:
    inputs:
      version:
        description: "The version of this deployment (ex: git commit sha)"
        required: true
        type: string
      use_green_environment:
        description: "Whether to use green environment for deployment"
        required: true
        type: boolean
      blue_desired_capacity:
        description: "Desired capacity for the blue environment (default: 2)"
        required: true
        type: number

jobs:
  upload_artifact:
    name: 📦 Upload Artifact to S3
    runs-on: ubuntu-latest
    outputs:
      s3_bucket: ${{ steps.upload.outputs.s3_bucket }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact-compressed-${{ inputs.version }}
          path: ./

      - name: Upload to S3
        id: upload
        run: |
          chmod +x ./util/scripts/backend/upload-to-s3.sh
          ./util/scripts/backend/upload-to-s3.sh "${{ inputs.version }}"

  deploy:
    name: 🚀 Blue/Green Deployment
    needs: upload_artifact
    runs-on: ubuntu-latest
    outputs:
      target_group_arn: ${{ steps.apply_bluegreen.outputs.target_group_arn }}
      asg_name: ${{ steps.apply_bluegreen.outputs.asg_name }}
      previous_version: ${{ steps.apply_bluegreen.outputs.previous_version }}
      previous_desired_capacity: ${{ steps.apply_bluegreen.outputs.previous_desired_capacity }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Apply Blue/Green Deployment
        id: apply_bluegreen
        run: |
          chmod +x ./util/scripts/backend/run-bluegreen-deploy-pipeline.sh
          ./util/scripts/backend/run-bluegreen-deploy-pipeline.sh "${{ inputs.version }}" "${{ inputs.blue_desired_capacity }}" "${{ inputs.use_green_environment }}"

  wait_for_health:
    name: 🩺 Health Check
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Wait for ALB Health Checks
        run: |
          chmod +x ./util/scripts/backend/wait-for-alb.sh
          ./util/scripts/backend/wait-for-alb.sh "${{ needs.deploy.outputs.target_group_arn }}" "${{ inputs.version }}"

  smoke_test:
    name: 🧪 Smoke Test
    needs: [deploy, wait_for_health]
    if: always() && (needs.wait_for_health.result == 'success')
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Smoke Tests
        run: |
          chmod +x ./util/scripts/backend/smoke-test.sh
          ./util/scripts/backend/smoke-test.sh https://decoupled-api.anyhasher.io "${{ inputs.use_green_environment }}"

  rollback:
    name: 🔄 Rollback
    needs: [deploy, smoke_test, wait_for_health]
    if: failure() && needs.wait_for_health.result == 'failure' || needs.smoke_test.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Rollback
        run: |
          chmod +x ./util/scripts/backend/run-bluegreen-deploy-pipeline.sh
          ./util/scripts/backend/run-bluegreen-deploy-pipeline.sh "${{ needs.deploy.outputs.previous_version }}" "${{ needs.deploy.outputs.previous_desired_capacity }}" "false"

      - name: Rollback Summary
        run: |
          chmod +x util/scripts/backend/rollback-summary.sh
          ./util/scripts/backend/rollback-summary.sh "${{ inputs.version }}" "${{ needs.deploy.outputs.previous_version }}" "${{ needs.deploy.outputs.asg_name }}" "${{ needs.deploy.outputs.previous_desired_capacity }}" "${{ needs.deploy.outputs.target_group_arn }}"

  promote_to_production:
    name: 🔥 Promote to Blue
    needs: [deploy, smoke_test, wait_for_health]
    if: success() && needs.wait_for_health.result == 'success' || needs.smoke_test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set green version to blue
        run: |
          chmod +x ./util/scripts/backend/run-bluegreen-deploy-pipeline.sh
          ./util/scripts/backend/run-bluegreen-deploy-pipeline.sh "${{ inputs.version }}" "${{ inputs.blue_desired_capacity }}" "false"

      - name: Deployment Success Summary
        run: |
          chmod +x util/scripts/backend/deployment-success-summary.sh
          ./util/scripts/backend/deployment-success-summary.sh "${{ inputs.version }}" "https://decoupled-api.anyhasher.io"
