name: CI/CD Workflow for Class

on:
  push:
    branch: olt

jobs:
  build:
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Deps
        run: cd frontend && npm install

      - name: Build the code
        run: cd frontend && npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: frontend/build

  test:
    name: 🧪 Run Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install deps
        run: cd frontend && npm i

      - name: Run the unit tests
        run: cd frontend && npm run test-ci
  
  lint:
    name: 🧼 Ensure Code Style
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install deps
        run: cd frontend && npm i

      - name: 😂 Lint code
        run: cd frontend && npm run lint