name: CI/CD Workflow for Class

on: 
  push:
    branch: olt

jobs:
  build: 
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: 16.x
      
      - run: cd frontend && npm i

      - run: cd frontend && npm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: frontend/build

