name: CI Workflow
on: 
  push:
    branch: olt
    
jobs:
  build: 
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with: 
          node-version: 16.x
      
      - name: Install Dependencies
        run: cd frontend && npm i

      - name: Transpile the code
        run: cd frontend && npm run build

      - name: Send to holding area
        uses: actions/upload-pages-artifact@v3 
        with:
          path: frontend/build


