# PLANNING STEPS:
# =====================
# Discover Changes
# Build Artifact
# Deploy Artifact
  # Create Infrastructure
  # Apply Configuration
  # Install App
  # Test New Version
  # Promote New Version
  # Kill Old Version
  
name: Rolling Deployment CI/CD Pipeline
run-name: "🛠️ ${{ github.event.head_commit.message }} (${{ github.sha }})"
on:
  push: 
    branches:
      - rolling-deployments   #normally 'main'

jobs:
  
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yml
    with:
      ref: ${{ github.sha }}    

  ci-backend:
    uses: ./.github/workflows/ci-backend.yml
    with:
      ref: ${{ github.sha }}    

# deploy frontend first since it doesn't need multiple instances
  cd-frontend:
    needs: [ci-frontend, ci-backend]
    uses: ./.github/workflows/cd-frontend.yml
    with: 
      ref: ${{ github.sha }}    
      backend_url: ${{ needs.cd-backend.outputs.backend_url }}
    secrets: inherit

# Set off chain reaction here, incrementing batch_id each time
# how will we know what the maximum batch_id is?
# backend deploy should include a "deregister" step for one instance
  cd-backend:
    needs: [cd-frontend]
    uses: ./.github/workflows/cd-backend.yml
    with: 
      ref: ${{ github.sha }}    
    secrets: inherit

# Promote no longer needed
  # promote:
  #   needs: [cd-frontend]
  #   uses: ./.github/workflows/promote.yml
  #   with: 
  #     ref: ${{ github.sha }}
  #     s3_bucket_hostname: ${{ needs.cd-frontend.outputs.s3_bucket_hostname }}
  #   secrets: inherit

# after backend has been completely rolled out and no old instances remain, we can clean up the old frontend

  cleanup-old-frontend:
    needs: [promote]
    uses: ./.github/workflows/cleanup.yml
    with: 
      ref: ${{ needs.promote.outputs.previous_ref }}
      env_name: Previous Blue
      reason: decommissioning
    secrets: inherit

# now, failure means rollback of any deployed instances and new frontend

  failure:
    needs: [cd-backend, cd-frontend, promote]
    # We need some extra logic to prevent cleanup when a CI failure
    if: |
      failure() && (
        needs.cd-backend.result != 'skipped' ||
        needs.cd-frontend.result != 'skipped' ||
        needs.promote.result != 'skipped'
      ) 
    uses: ./.github/workflows/cleanup.yml
    with: 
      ref: ${{ github.sha }}
      env_name: Green
      reason: failure
    secrets: inherit