# PLANNING STEPS:
# =====================
# Discover Changes
# Build Artifacts
# Deploy Artifacts
# Deploy Frontend
# Start Rolling Out Backend Instances (chain reaction)
## Create Infrastructure
## Apply Configuration
## Install App
## Test New Version
## Add to Load Balancer
## Kill One Old Instance
## Repeat

name: Rolling Deployment CI/CD Pipeline
run-name: "🛠️ ${{ github.event.head_commit.message }} (${{ github.sha }})"
on:
  push:
    branches:
      # - main
      - rolling-deployments #normally 'main'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.event.before }}
          filters: |
            frontend:
              - 'frontend/**'
              - '.github/workflows/ci-frontend.yml'
              - '.github/workflows/cd-frontend.yml'
            backend:
              - 'backend/**'
              - '.github/workflows/ci-backend.yml'
              - '.github/workflows/cd-backend.yml'

  ci-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    uses: .github/workflows/ci-frontend.yml@rolling-deployments
    with:
      ref: ${{ github.sha }}

  ci-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    uses: ./.github/workflows/ci-backend.yml@rolling-deployments
    with:
      ref: ${{ github.sha }}

  cd-frontend:
    needs: ci-frontend
    uses: ./.github/workflows/cd-frontend.yml@rolling-deployments
    with:
      ref: ${{ github.sha }}
      backend_url: api.anyhasher.io
    secrets: inherit

  cd-backend:
    needs: ci-backend
    uses: ./.github/workflows/cd-backend.yml@rolling-deployments
    with:
      version: ${{ github.sha }}
    secrets: inherit
